import { Router } from "express";

// NOTE: `auth.ts` uses `export = router` (CommonJS-style), so we import it with `require` syntax.
import authRouter = require("./auth");

import bankRouter from "./bank";
import accountGroupRouter from "./accountGroup";
import accountHeadRouter from "./accountHead";
import accountSubheadRouter from "./accountSubhead";
import accountChartRouter from "./accountChart";
import accountTransactionRouter from "./accountTransaction";
import defaulSubheadSettingsRouter from "./defaulSubheadSettings";
import defaultAccountSettingsRouter from "./defaultAccountSettings";
import billingItemRouter from "./billingItem";
import concessionDiscountRouter from "./concessionDiscount";
import classDefaultBillingRouter from "./classDefaultBilling";
import studentBillingRouter from "./studentBilling";
import studentConcessionDiscountRouter from "./studentConcessionDiscount";
import tempJournalTransferRouter from "./tempJournalTransfer";

import uploadRouter from "./upload";
import categoryRouter from "./category";
import subCategoryRouter from "./subCategory";
import brandRouter from "./brand";
import menuRouter from "./menu";
import appRoleRouter from "./appRole";
import privilegeRouter from "./privilege";
import uomRouter from "./uom";
import inventoryItemRouter from "./inventoryItem";
import supplierRouter from "./supplier";
import purchaseRouter from "./purchase";
import salesRouter from "./sales";
import studentCollectionRouter from "./studentCollection";
import staffCollectionRouter from "./staffCollection";
import donationRouter from "./donation";
import schoolClassRouter from "./schoolClass";
import studentRouter from "./student";
import subClassRouter from "./subClass";
import termRouter from "./term";
import sessionRouter from "./session";
import activePeriodRouter from "./activePeriod";
import defaultBillingPeriodRouter from "./defaultBillingPeriod";
import staffRouter from "./staff";
import projectRouter from "./project";
import projectCollectionRouter from "./projectCollection";
import storeRouter from "./store";
import userStoreRouter from "./userStore";
import storeTransferRouter from "./storeTransfer";
import facilityRouter from "./facility";
import facilityCollectionRouter from "./facilityCollection";
import cashierRouter from "./cashier";
import inventoryReceiveAcknowledgementRouter from "./inventoryReceiveAcknowledgement";
import userRouter from "./user";
import auditLogRouter from "./auditLog";
import departmentRouter from "./department";
import gradeLevelRouter from "./gradeLevel";
import staffBankDetailsRouter from "./staffBankDetails";
import salaryComponentRouter from "./salaryComponent";
import salaryChartRouter from "./salaryChart";
import staffSalaryOverrideComponentRouter from "./staffSalaryOverrideComponent";
import payrollRouter from "./payroll";
import activePayrollPeriodRouter from "./activePayrollPeriod";
import administrativeExpenseComponentRouter from "./administrativeExpenseComponent";
import administrativeExpenseRouter from "./administrativeExpense";
import assessmentTemplateRouter from "./assessmentTemplate";
import assessmentComponentRouter from "./assessmentComponent";
import classAssessmentTemplateRouter from "./classAssessmentTemplate";
import subjectRouter from "./subject";
import classSubjectRouter from "./classSubject";
import studentSubjectRegistrationRouter from "./studentSubjectRegistration";
import studentAssessmentScoreRouter from "./studentAssessmentScore";
import gradingTemplateRouter from "./gradingTemplate";
import gradingTemplateItemRouter from "./gradingTemplateItem";
import behaviouralAssessmentTemplateRouter from "./behaviouralAssessmentTemplate";
import behaviouralAssessmentComponentRouter from "./behaviouralAssessmentComponent";
import behaviouralGradingTemplateRouter from "./behaviouralGradingTemplate";
import behaviouralGradingItemRouter from "./behaviouralGradingItem";
import studentBehaviouralAssessmentScoreRouter from "./studentBehaviouralAssessmentScore";
import assessmentRemarksRouter from "./assessmentRemarks";
import defaultClassRemarkSetupRouter from "./defaultClassRemarkSetup";
import assignmentRouter from "./assignment";
import studentAssignmentRouter from "./studentAssignment";
import teacherSubjectRouter from "./teacherSubject";
import attendanceRecordRouter from "./attendanceRecord";
import routeRouter from "./route";
import vehicleRouter from "./vehicle";
import vehicleRouteRouter from "./vehicleRoute";
import bustopRouter from "./bustop";
import routeBustopRouter from "./routeBustop";
import vehicleTripRouter from "./vehicleTrip";
import studentTransportRouter from "./studentTransport";
import studentTransportationRegisterRouter from "./studentTransportationRegister";
import { authenticateJWT } from "../middlewares/auth";
import { requirePrivilege } from "../middlewares/requirePrivilege";

const router = Router();

router.use("/auth", authRouter);

// Protected API: JWT first, then privilege check (user id comes from token, not request params)
router.use(authenticateJWT);
// router.use(requirePrivilege);
router.use("/banks", bankRouter);
router.use("/account-groups", accountGroupRouter);
router.use("/account-heads", accountHeadRouter);
router.use("/account-subheads", accountSubheadRouter);
router.use("/account-charts", accountChartRouter);
router.use("/account-transactions", accountTransactionRouter);
router.use("/default-subhead-settings", defaulSubheadSettingsRouter);
router.use("/default-account-settings", defaultAccountSettingsRouter);
router.use("/billing-items", billingItemRouter);
router.use("/concession-discounts", concessionDiscountRouter);
router.use("/class-default-billings", classDefaultBillingRouter);
router.use("/student-billings", studentBillingRouter);
router.use("/student-concession-discounts", studentConcessionDiscountRouter);
router.use("/temp-journal-transfers", tempJournalTransferRouter);
router.use("/categories", categoryRouter);
router.use("/sub-categories", subCategoryRouter);
router.use("/brands", brandRouter);
router.use("/menus", menuRouter);
router.use("/app-roles", appRoleRouter);
router.use("/privileges", privilegeRouter);
router.use("/uoms", uomRouter);
router.use("/inventory-items", inventoryItemRouter);
router.use("/suppliers", supplierRouter);
router.use("/purchases", purchaseRouter);
router.use("/sales", salesRouter);
router.use("/student-collections", studentCollectionRouter);
router.use("/staff-collections", staffCollectionRouter);
router.use("/donations", donationRouter);
router.use("/school-classes", schoolClassRouter);
router.use("/students", studentRouter);
router.use("/sub-classes", subClassRouter);
router.use("/terms", termRouter);
router.use("/sessions", sessionRouter);
router.use("/active-period", activePeriodRouter);
router.use("/default-billing-period", defaultBillingPeriodRouter);
router.use("/staff", staffRouter);
router.use("/projects", projectRouter);
router.use("/project-collections", projectCollectionRouter);
router.use("/stores", storeRouter);
router.use("/user-stores", userStoreRouter);
router.use("/store-transfers", storeTransferRouter);
router.use("/facilities", facilityRouter);
router.use("/facility-collections", facilityCollectionRouter);
router.use("/cashiers", cashierRouter);
router.use("/inventory-receive-acknowledgements", inventoryReceiveAcknowledgementRouter);
router.use("/users", userRouter);
router.use("/audit-logs", auditLogRouter);
router.use("/departments", departmentRouter);
router.use("/grade-levels", gradeLevelRouter);
router.use("/staff-bank-details", staffBankDetailsRouter);
router.use("/salary-components", salaryComponentRouter);
router.use("/salary-charts", salaryChartRouter);
router.use("/staff-salary-override-components", staffSalaryOverrideComponentRouter);
router.use("/payroll", payrollRouter);
router.use("/active-payroll-period", activePayrollPeriodRouter);
router.use("/administrative-expense-components", administrativeExpenseComponentRouter);
router.use("/administrative-expenses", administrativeExpenseRouter);
router.use("/assessment-templates", assessmentTemplateRouter);
router.use("/assessment-components", assessmentComponentRouter);
router.use("/class-assessment-templates", classAssessmentTemplateRouter);
router.use("/subjects", subjectRouter);
router.use("/class-subjects", classSubjectRouter);
router.use("/student-subject-registrations", studentSubjectRegistrationRouter);
router.use("/student-assessment-scores", studentAssessmentScoreRouter);
router.use("/grading-templates", gradingTemplateRouter);
router.use("/grading-template-items", gradingTemplateItemRouter);
router.use("/behavioural-assessment-templates", behaviouralAssessmentTemplateRouter);
router.use("/behavioural-assessment-components", behaviouralAssessmentComponentRouter);
router.use("/behavioural-grading-templates", behaviouralGradingTemplateRouter);
router.use("/behavioural-grading-items", behaviouralGradingItemRouter);
router.use("/student-behavioural-assessment-scores", studentBehaviouralAssessmentScoreRouter);
router.use("/assessment-remarks", assessmentRemarksRouter);
router.use("/default-class-remark-setups", defaultClassRemarkSetupRouter);
router.use("/assignments", assignmentRouter);
router.use("/student-assignments", studentAssignmentRouter);
router.use("/teacher-subjects", teacherSubjectRouter);
router.use("/attendance-records", attendanceRecordRouter);
router.use("/routes", routeRouter);
router.use("/vehicles", vehicleRouter);
router.use("/vehicle-routes", vehicleRouteRouter);
router.use("/bustops", bustopRouter);
router.use("/route-bustops", routeBustopRouter);
router.use("/vehicle-trips", vehicleTripRouter);
router.use("/student-transports", studentTransportRouter);
router.use("/student-transportation-registers", studentTransportationRegisterRouter);

router.use("/upload", uploadRouter);

export default router;
