import { Router } from "express";

// NOTE: `auth.ts` uses `export = router` (CommonJS-style), so we import it with `require` syntax.
import authRouter = require("./auth");

import bankRouter from "./bank";
import accountGroupRouter from "./accountGroup";
import accountHeadRouter from "./accountHead";
import accountSubheadRouter from "./accountSubhead";
import accountChartRouter from "./accountChart";
import accountTransactionRouter from "./accountTransaction";
import defaulSubheadSettingsRouter from "./defaulSubheadSettings";
import defaultAccountSettingsRouter from "./defaultAccountSettings";
import billingItemRouter from "./billingItem";
import concessionDiscountRouter from "./concessionDiscount";
import classDefaultBillingRouter from "./classDefaultBilling";
import studentBillingRouter from "./studentBilling";
import studentConcessionDiscountRouter from "./studentConcessionDiscount";
import tempJournalTransferRouter from "./tempJournalTransfer";

import uploadRouter from "./upload";
import categoryRouter from "./category";
import subCategoryRouter from "./subCategory";
import brandRouter from "./brand";
import menuRouter from "./menu";
import appRoleRouter from "./appRole";
import privilegeRouter from "./privilege";
import uomRouter from "./uom";
import inventoryItemRouter from "./inventoryItem";
import supplierRouter from "./supplier";
import purchaseRouter from "./purchase";
import salesRouter from "./sales";
import studentCollectionRouter from "./studentCollection";
import staffCollectionRouter from "./staffCollection";
import donationRouter from "./donation";
import schoolClassRouter from "./schoolClass";
import studentRouter from "./student";
import subClassRouter from "./subClass";
import termRouter from "./term";
import sessionRouter from "./session";
import activePeriodRouter from "./activePeriod";
import defaultBillingPeriodRouter from "./defaultBillingPeriod";
import staffRouter from "./staff";
import projectRouter from "./project";
import projectCollectionRouter from "./projectCollection";
import storeRouter from "./store";
import userStoreRouter from "./userStore";
import storeTransferRouter from "./storeTransfer";
import facilityRouter from "./facility";
import facilityCollectionRouter from "./facilityCollection";
import cashierRouter from "./cashier";
import inventoryReceiveAcknowledgementRouter from "./inventoryReceiveAcknowledgement";
import userRouter from "./user";
import auditLogRouter from "./auditLog";
import departmentRouter from "./department";
import gradeLevelRouter from "./gradeLevel";
import staffBankDetailsRouter from "./staffBankDetails";
import salaryComponentRouter from "./salaryComponent";
import salaryChartRouter from "./salaryChart";
import staffSalaryOverrideComponentRouter from "./staffSalaryOverrideComponent";
import { authenticateJWT } from "../middlewares/auth";
import { requirePrivilege } from "../middlewares/requirePrivilege";

const router = Router();

router.use("/auth", authRouter);

// Protected API: JWT first, then privilege check (user id comes from token, not request params)
router.use(authenticateJWT);
// router.use(requirePrivilege);
router.use("/banks", bankRouter);
router.use("/account-groups", accountGroupRouter);
router.use("/account-heads", accountHeadRouter);
router.use("/account-subheads", accountSubheadRouter);
router.use("/account-charts", accountChartRouter);
router.use("/account-transactions", accountTransactionRouter);
router.use("/default-subhead-settings", defaulSubheadSettingsRouter);
router.use("/default-account-settings", defaultAccountSettingsRouter);
router.use("/billing-items", billingItemRouter);
router.use("/concession-discounts", concessionDiscountRouter);
router.use("/class-default-billings", classDefaultBillingRouter);
router.use("/student-billings", studentBillingRouter);
router.use("/student-concession-discounts", studentConcessionDiscountRouter);
router.use("/temp-journal-transfers", tempJournalTransferRouter);
router.use("/categories", categoryRouter);
router.use("/sub-categories", subCategoryRouter);
router.use("/brands", brandRouter);
router.use("/menus", menuRouter);
router.use("/app-roles", appRoleRouter);
router.use("/privileges", privilegeRouter);
router.use("/uoms", uomRouter);
router.use("/inventory-items", inventoryItemRouter);
router.use("/suppliers", supplierRouter);
router.use("/purchases", purchaseRouter);
router.use("/sales", salesRouter);
router.use("/student-collections", studentCollectionRouter);
router.use("/staff-collections", staffCollectionRouter);
router.use("/donations", donationRouter);
router.use("/school-classes", schoolClassRouter);
router.use("/students", studentRouter);
router.use("/sub-classes", subClassRouter);
router.use("/terms", termRouter);
router.use("/sessions", sessionRouter);
router.use("/active-period", activePeriodRouter);
router.use("/default-billing-period", defaultBillingPeriodRouter);
router.use("/staff", staffRouter);
router.use("/projects", projectRouter);
router.use("/project-collections", projectCollectionRouter);
router.use("/stores", storeRouter);
router.use("/user-stores", userStoreRouter);
router.use("/store-transfers", storeTransferRouter);
router.use("/facilities", facilityRouter);
router.use("/facility-collections", facilityCollectionRouter);
router.use("/cashiers", cashierRouter);
router.use("/inventory-receive-acknowledgements", inventoryReceiveAcknowledgementRouter);
router.use("/users", userRouter);
router.use("/audit-logs", auditLogRouter);
router.use("/departments", departmentRouter);
router.use("/grade-levels", gradeLevelRouter);
router.use("/staff-bank-details", staffBankDetailsRouter);
router.use("/salary-components", salaryComponentRouter);
router.use("/salary-charts", salaryChartRouter);
router.use("/staff-salary-override-components", staffSalaryOverrideComponentRouter);

router.use("/upload", uploadRouter);

export default router;
