import {
  InvoiceStatus,
  InvoiceType,
  LoanStatus,
  LoanType,
  MerchantTransactionType,
  TransactionStatus,
  MandateStatus,
  DirectPayStatus,
  RevenueType,
} from "@prisma/client";
import { loanService } from "./loanService";
import { LoanSettingService } from "./loanSettingService";
import { MerchantTransactionService } from "./merchantTransactionService";
import { emailService } from "./emailService";
import { RevenueService } from "./revenueService";
import { invoiceMandateService } from "./invoiceMandateService";
import { randomBytes } from "crypto";
import { accountDetailsService } from "./accountDetailsService";
import { directPayService } from "./directPayService";
import prisma from "../utils/prisma";

const loanSettingService = new LoanSettingService();
const merchantTransactionService = new MerchantTransactionService();
const revenueService = new RevenueService();

// ==================== HELPER FUNCTIONS ====================

/**
 * Generate a short alphanumeric reference ID (max 24 characters)
 * @returns A string containing only alphanumeric characters (0-9, A-Z)
 */
export const generateShortReferenceId = (): string => {
  // Generate 12 random bytes (96 bits) for good entropy
  const bytes = randomBytes(12);
  // Convert to hex and then map to alphanumeric (0-9, A-Z)
  // Hex gives us 24 characters, we'll convert a-f to A-F and keep 0-9
  const hex = bytes.toString("hex").toUpperCase();

  // Take first 24 characters (hex is always 24 chars for 12 bytes)
  // Hex already contains only 0-9 and A-F, which are alphanumeric
  return hex.substring(0, 24);
};

// ==================== INTERFACES ====================

export interface CreateItemInput {
  description: string;
  quantity: number;
  amount: number;
}

export interface UpdateItemInput {
  description?: string;
  quantity?: number;
  amount?: number;
}

export interface CreateInvoiceInput {
  customerName: string;
  customerEmail: string;
  customerPhoneNumber: string;
  dueDate: Date | string;
  note?: string;
  amount: number;
  buyerId?: string;
  merchantId: string;
  items: CreateItemInput[];
  status?: InvoiceStatus;
  type?: InvoiceType;
}

export interface UpdateInvoiceInput {
  customerName?: string;
  customerEmail?: string;
  customerPhoneNumber?: string;
  dueDate?: Date | string;
  note?: string;
  amount?: number;
  buyerId?: string;
  status?: InvoiceStatus;
  type?: InvoiceType;
  items?: UpdateItemInput[];
}

// ==================== SELECT OBJECTS ====================

const invoiceSelect = {
  id: true,
  liftpayId: true,
  customerName: true,
  customerEmail: true,
  customerPhoneNumber: true,
  dueDate: true,
  note: true,
  amount: true,
  buyerId: true,
  merchantId: true,
  status: true,
  type: true,
  createdAt: true,
  updatedAt: true,
} as const;

const itemSelect = {
  id: true,
  invoiceId: true,
  description: true,
  quantity: true,
  amount: true,
  createdAt: true,
  updatedAt: true,
} as const;

const INTERST_RATE = process.env.INTERST_RATE || 7.5;
// ==================== INVOICE SERVICE ====================

export class InvoiceService {
  // ==================== INVOICE CRUD ====================

  /**
   * Create a new invoice with items
   */
  async createInvoice(input: CreateInvoiceInput) {
    try {
      // Validate merchant exists
      const merchant = await prisma.merchant.findUnique({
        where: { id: input.merchantId },
      });

      if (!merchant) {
        throw new Error("Merchant not found");
      }

      // Validate buyer if provided
      if (input.buyerId) {
        const buyer = await prisma.buyer.findUnique({
          where: { id: input.buyerId },
        });

        if (!buyer) {
          throw new Error("Buyer not found");
        }
      }

      // Validate items
      if (!input.items || input.items.length === 0) {
        throw new Error("Invoice must have at least one item");
      }

      // Create invoice with items
      const invoice = await prisma.invoice.create({
        data: {
          liftpayId: "", // Will be auto-generated by trigger
          customerName: input.customerName,
          customerEmail: input.customerEmail,
          customerPhoneNumber: input.customerPhoneNumber,
          dueDate: new Date(input.dueDate),
          note: input.note,
          amount: input.amount,
          buyerId: input.buyerId,
          merchantId: input.merchantId,
          status: input.status || InvoiceStatus.Pending,
          type: input.type || InvoiceType.Purchase,
          items: {
            create: input.items.map((item) => ({
              description: item.description,
              quantity: item.quantity,
              amount: item.amount,
            })),
          },
        },
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              liftpayId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
        },
      });

      // Send invoice email to customer
      try {
        const formattedDueDate = new Date(invoice.dueDate).toLocaleDateString(
          "en-US",
          {
            year: "numeric",
            month: "long",
            day: "numeric",
          }
        );

        const formattedItems = invoice.items.map((item) => ({
          description: item.description,
          quantity: item.quantity,
          amount: Number(item.amount).toLocaleString("en-US", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          }),
        }));

        const formattedTotal = Number(invoice.amount).toLocaleString("en-US", {
          minimumFractionDigits: 2,
          maximumFractionDigits: 2,
        });
        emailService.sendTemplateEmail({
          to: invoice.customerEmail,
          templateName: "invoiceCreated",
          subject: `New Invoice from ${invoice.merchant.businessName} - ${invoice.liftpayId}`,
          data: {
            customer_name: invoice.customerName,
            merchant_name: invoice.merchant.businessName,
            merchant_email: invoice.merchant.businessEmail,
            invoice_id: invoice.liftpayId,
            due_date: formattedDueDate,
            items: formattedItems,
            total_amount: formattedTotal,
            note: invoice.note || "",
            invoice_link: `${
              process.env.FRONTEND_URL || "https://liftpay.co"
            }/buyer/dashboard/invoices`,
          },
        });
      } catch (emailError: any) {
        // Log email error but don't fail the invoice creation
        console.error("Failed to send invoice email:", emailError.message);
      }

      return {
        success: true,
        message: "Invoice created successfully",
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to create invoice",
      };
    }
  }

  /**
   * Get invoice by ID
   */
  async getInvoiceById(id: string) {
    try {
      const invoice = await prisma.invoice.findUnique({
        where: { id },
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              liftpayId: true,
              firstName: true,
              lastName: true,
              email: true,
              phoneNumber: true,
            },
          },
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
              businessPhone: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
      });

      if (!invoice) {
        throw new Error("Invoice not found");
      }

      return {
        success: true,
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoice",
      };
    }
  }

  /**
   * Get invoice by liftpayId
   */
  async getInvoiceByLiftpayId(liftpayId: string) {
    try {
      const invoice = await prisma.invoice.findUnique({
        where: { liftpayId },
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              liftpayId: true,
              firstName: true,
              lastName: true,
              email: true,
              phoneNumber: true,
            },
          },
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
              businessPhone: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
      });

      if (!invoice) {
        throw new Error("Invoice not found");
      }

      return {
        success: true,
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoice",
      };
    }
  }

  /**
   * Get all invoices with optional filters
   */
  async getAllInvoices(filters?: {
    merchantId?: string;
    buyerId?: string;
    status?: InvoiceStatus;
    customerEmail?: string;
    type?: InvoiceType;
    page?: number;
    limit?: number;
  }) {
    try {
      const page = filters?.page || 1;
      const limit = filters?.limit || 10;
      const skip = (page - 1) * limit;

      const where: any = {};
      if (filters?.merchantId) where.merchantId = filters.merchantId;
      if (filters?.buyerId) where.buyerId = filters.buyerId;
      if (filters?.status) where.status = filters.status;
      if (filters?.customerEmail) where.customerEmail = filters.customerEmail;
      if (filters?.type) where.type = filters.type;

      const [invoices, total] = await Promise.all([
        prisma.invoice.findMany({
          where,
          skip,
          take: limit,
          include: {
            items: true,
            buyer: {
              select: {
                id: true,
                liftpayId: true,
                firstName: true,
                lastName: true,
                email: true,
              },
            },
            merchant: {
              select: {
                id: true,
                liftpayId: true,
                businessName: true,
                businessEmail: true,
              },
            },
            loan: {
              select: {
                id: true,
                downPaymentAmount: true,
                loanAmount: true,
                loanTenure: true,
                monthlyRepayment: true,
              },
            },
          },
          orderBy: { createdAt: "desc" },
        }),
        prisma.invoice.count({ where }),
      ]);

      return {
        success: true,
        data: {
          invoices,
          pagination: {
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit),
          },
        },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoices",
      };
    }
  }

  /**
   * Get invoices by merchant ID
   */
  async getInvoicesByMerchantId(merchantId: string, status?: InvoiceStatus) {
    try {
      const where: any = { merchantId };
      if (status) where.status = status;

      const invoices = await prisma.invoice.findMany({
        where,
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              liftpayId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
        orderBy: { createdAt: "desc" },
      });

      return {
        success: true,
        data: invoices,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoices",
      };
    }
  }

  /**
   * Get invoices by buyer ID
   */
  async getInvoicesByBuyerId(buyerId: string, status?: InvoiceStatus) {
    try {
      const where: any = { buyerId };
      if (status) where.status = status;
      const invoices = await prisma.invoice.findMany({
        where,
        include: {
          items: true,
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
        orderBy: { createdAt: "desc" },
      });

      return {
        success: true,
        data: invoices,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoices",
      };
    }
  }

  /**
   * Get invoices by customer email
   */
  async getInvoicesByCustomerEmail(
    customerEmail: string,
    status?: InvoiceStatus
  ) {
    try {
      const where: any = { customerEmail };
      if (status) where.status = status;

      const invoices = await prisma.invoice.findMany({
        where,
        include: {
          items: true,
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
          buyer: {
            select: {
              id: true,
              liftpayId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          loan: {
            select: {
              id: true,
              downPaymentAmount: true,
              loanAmount: true,
              loanTenure: true,
              monthlyRepayment: true,
            },
          },
        },
        orderBy: { createdAt: "desc" },
      });

      return {
        success: true,
        data: invoices,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoices",
      };
    }
  }

  /**
   * Update invoice
   */
  async finalizeAfterUpfrontAndMandate(mandateId: string) {
    // Re-fetch mandate and verify upfront payment if needed, then update invoice, create loan, and record revenue/merchant transaction
    const mandate = await prisma.invoiceMandate.findUnique({
      where: { id: mandateId },
    });
    if (!mandate) {
      throw new Error("Mandate not found");
    }

    // check upfront payment
    const upfrontPayment = await directPayService.getDirectPaysByMandateId(
      mandate.id
    );
    if (!upfrontPayment) {
      throw new Error("Upfront payment not found");
    }
    if (upfrontPayment?.length > 0 && upfrontPayment[0].status != "Completed") {
      const validateUpfrontPayment = await directPayService.verifyMonoDirectPay(
        upfrontPayment[0].reference
      );
      if (
        !validateUpfrontPayment.success &&
        validateUpfrontPayment.data.status !== "successful"
      ) {
        return {
          success: false,
          message: "Upfront payment not yet completed",
          data: validateUpfrontPayment.data,
        };
      }
    }
    const buyerId = mandate.buyerId;
    const mandateInvoiceId = mandate.invoiceId;
    const mandateDownPayment = mandate.downPayment;
    const mandateTenure = mandate.tenure;

    const buyer = await prisma.buyer.findUnique({
      where: { id: buyerId },
    });
    if (!buyer) {
      throw new Error("Buyer not found");
    }
    const invoice = await prisma.invoice.findUnique({
      where: { id: mandateInvoiceId },
    });
    if (!invoice) {
      throw new Error("Invoice not found");
    }
    const eligibilityAndScore =
      await loanSettingService.liveEligibilityPurchase({
        purchaseAmount: Number(invoice.amount),
        downPaymentAmount: Number(mandateDownPayment),
        months: Number(mandateTenure),
        buyerId: buyerId,
      });
    if (!eligibilityAndScore) {
      throw new Error("Eligibility and score not found");
    }

    const updateData: any = {
      status: InvoiceStatus.Paid,
      buyerId: buyerId,
      customerName: `${buyer.firstName} ${buyer.lastName}`,
      customerEmail: buyer.email,
      customerPhoneNumber: buyer.phoneNumber,
    };
    

    if (!("approved" in eligibilityAndScore) || !eligibilityAndScore.approved) {
      return {
        success: false,
        message: "Eligibility and score not valid",
        data: eligibilityAndScore,
      };
    }

    const updatedInvoice = await prisma.invoice.update({
      where: { id: mandateInvoiceId },
      data: updateData,
      include: {
        items: true,
      },
    });

    // get loan by invoice number
    const loan = await loanService.getLoanByInvoiceId(mandateInvoiceId);
    if (loan && loan.success) {
      return {
        success: true,
        message: "Invoice updated successfully",
        data: {
          invoice: updatedInvoice,
          loan: loan.data,
        },
      };
    }
    const loanResult = await loanService.createLoan({
      buyerId: buyerId,
      loanAmount: eligibilityAndScore.approvedLoanAmount,
      loanTenure: Number(mandateTenure),
      loanStartDate: new Date(),
      loanStatus: LoanStatus.Active,
      loanType: LoanType.Personal,
      loanInterestRate: Number(INTERST_RATE),
      loanPurpose: "Loan",
      purchaseAmount: Number(invoice.amount),
      downPaymentAmount: eligibilityAndScore.requiredDownPayment,
      merchantId: invoice.merchantId,
      referenceNumber: invoice.liftpayId,
      adminCharge: eligibilityAndScore.adminCharge,
      insurance: eligibilityAndScore.insurance,
      monthlyRepayment: eligibilityAndScore.monthlyRepayment,
      invoiceId: mandateInvoiceId,
    });

    if (!loanResult.success) {
      return {
        success: false,
        message:
          loanResult.error || "Failed to create loan after approving invoice",
      };
    }
    // perform merchant payment
    await merchantTransactionService.createMerchantTransaction({
      merchantId: invoice.merchantId,
      invoiceRef: invoice.id,
      credit: Number(invoice.amount),
      debit: 0,
      transactionType: MerchantTransactionType.Credit,
      description: `invoice credit on ${invoice.id}`,
      status: TransactionStatus.Completed,
      transactionDate: new Date(),
      groupReference: invoice.liftpayId,
    });
    await revenueService.createRevenue({
      type: RevenueType.DownPayment,
      credit: eligibilityAndScore.requiredDownPayment,
      debit: 0,
      description: `Down payment for loan ${invoice.liftpayId}`,
      parentTable: "invoice",
      referenceIds: [invoice.id],
      detail: `Down payment for loan ${invoice.liftpayId}`,
      buyerId: buyerId,
      transactionDate: new Date(),
    });

    return {
      success: true,
      message: "Invoice updated successfully",
      data: {
        invoice: updatedInvoice,
        loan: loanResult.data,
      },
    };
  }
  async updateInvoice(id: string, input: UpdateInvoiceInput) {
    try {
      const existingInvoice = await prisma.invoice.findUnique({
        where: { id },
      });

      if (!existingInvoice) {
        throw new Error("Invoice not found");
      }

      // Validate buyer if provided
      if (input.buyerId) {
        const buyer = await prisma.buyer.findUnique({
          where: { id: input.buyerId },
        });

        if (!buyer) {
          throw new Error("Buyer not found");
        }
      }

      const updateData: any = {};
      if (input.customerName !== undefined)
        updateData.customerName = input.customerName;
      if (input.customerEmail !== undefined)
        updateData.customerEmail = input.customerEmail;
      if (input.customerPhoneNumber !== undefined)
        updateData.customerPhoneNumber = input.customerPhoneNumber;
      if (input.dueDate !== undefined)
        updateData.dueDate = new Date(input.dueDate);
      if (input.note !== undefined) updateData.note = input.note;
      if (input.amount !== undefined) updateData.amount = input.amount;
      if (input.buyerId !== undefined) updateData.buyerId = input.buyerId;
      if (input.status !== undefined) updateData.status = input.status;
      if (input.type !== undefined) updateData.type = input.type;

      const invoice = await prisma.invoice.update({
        where: { id },
        data: updateData,
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              liftpayId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
        },
      });
      //update items
      await prisma.item.deleteMany({
        where: { invoiceId: id },
      });
      if (input.items) {
        for (const item of input.items) {
          await prisma.item.create({
            data: {
              invoiceId: id,
              description: item.description || "",
              quantity: item.quantity || 0,
              amount: item.amount || 0,
            },
          });
        }
      }

      return {
        success: true,
        message: "Invoice updated successfully",
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to update invoice",
      };
    }
  }

  /**
   * Update invoice status
   */
  async updateInvoiceStatus(id: string, status: InvoiceStatus) {
    try {
      const existingInvoice = await prisma.invoice.findUnique({
        where: { id },
      });

      if (!existingInvoice) {
        throw new Error("Invoice not found");
      }

      const invoice = await prisma.invoice.update({
        where: { id },
        data: { status },
        include: {
          items: true,
          buyer: {
            select: {
              id: true,
              liftpayId: true,
              firstName: true,
              lastName: true,
              email: true,
            },
          },
          merchant: {
            select: {
              id: true,
              liftpayId: true,
              businessName: true,
              businessEmail: true,
            },
          },
        },
      });

      return {
        success: true,
        message: `Invoice marked as ${status.toLowerCase()}`,
        data: invoice,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to update invoice status",
      };
    }
  }

  /**
   * Delete invoice (and cascade delete items)
   */
  async deleteInvoice(id: string) {
    try {
      const existingInvoice = await prisma.invoice.findUnique({
        where: { id },
        include: { items: true },
      });

      if (!existingInvoice) {
        throw new Error("Invoice not found");
      }

      await prisma.invoice.delete({
        where: { id },
      });

      return {
        success: true,
        message: "Invoice deleted successfully",
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to delete invoice",
      };
    }
  }

  /**
   * Update invoice
   */
  async approveAndCreateLoanInvoice(
    id: string,
    loanTenure: number,
    downPaymentAmount: number,
    buyerId: string
  ): Promise<any>;
  async approveAndCreateLoanInvoice(
    id: string,
    loanTenure: number,
    downPaymentAmount: number,
    buyerId: string,
    regenerateMandate: boolean
  ): Promise<any>;
  async approveAndCreateLoanInvoice(
    id: string,
    loanTenure: number,
    downPaymentAmount: number,
    buyerId: string,
    regenerateMandate: boolean = false
  ) {
    const buyer = await prisma.buyer.findUnique({
      where: { id: buyerId },
    });
    if (!buyer) {
      throw new Error("Buyer not found");
    }
    const invoice = await prisma.invoice.findUnique({
      where: { id: id },
    });
    if (!invoice) {
      throw new Error("Invoice not found");
    }
    const eligibilityAndScore =
      await loanSettingService.liveEligibilityPurchase({
        purchaseAmount: Number(invoice.amount),
        downPaymentAmount: downPaymentAmount,
        months: loanTenure,
        buyerId: buyerId,
      });
    if (!eligibilityAndScore) {
      throw new Error("Eligibility and score not found");
    }

    const updateData: any = {
      status: InvoiceStatus.Pending,
      buyerId: buyerId,
      customerName: `${buyer.firstName} ${buyer.lastName}`,
      customerEmail: buyer.email,
      customerPhoneNumber: buyer.phoneNumber,
    };

    if (!("approved" in eligibilityAndScore) || !eligibilityAndScore.approved) {
      return {
        success: false,
        message: "Eligibility and score not valid",
        data: eligibilityAndScore,
      };
    }

    //Before creating the loan, check if mandate exists for the invoice and downpayment already paid

    const updatedInvoice = await prisma.invoice.update({
      where: { id: id },
      data: updateData,
      include: {
        items: true,
      },
    });

    // create invoice mandate
    //generate short alphanumeric referenceId (max 24 characters)
    const referenceId = generateShortReferenceId();

    // get latest account details for the buyer
    const latestAccountDetails =
      await accountDetailsService.getLatestAccountDetailsByBuyerId(buyerId);
    if (!latestAccountDetails) {
      throw new Error("Account details not yet linked to the buyer");
    }
    const accountDetails = await accountDetailsService.getMonoAccountById(
      latestAccountDetails.data?.accountId || ""
    );
    if (!accountDetails) {
      throw new Error("Account not found for the buyer! Try linking the account to the buyer.");
    }
    //
    let updateMandateUrl = "";
  
    const mandate = await invoiceMandateService.getMandatesByInvoiceId(id);
    if (mandate?.length > 0) {
      updateMandateUrl = mandate[0].updateMandateUrl || "";

      if (mandate[0].status != "Active" || regenerateMandate==true) {
        // cancel the mandate
        await accountDetailsService.cancelMonoMandate(
          mandate[0].monoMandateId || ""
        );
        const createEmandate =
          await accountDetailsService.createVariableMandate(
            process.env.MONO_CUSTOMER_ID_FOR_TEST ||
              accountDetails.data?.data?.customer?.id ||
              "",
            Math.ceil(Number(eligibilityAndScore.monthlyRepayment) * 100),
            new Date().toISOString(),
            referenceId
          );

          
        // update the mandate
        await invoiceMandateService.updateInvoiceMandate(mandate[0].id, {
          monoMandateId: createEmandate.data?.data?.mandate_id || "",
          status: MandateStatus.Pending,
          updateMandateUrl: createEmandate.data?.data?.mono_url,
          monoAccountId: accountDetails.data?.data?.account?.id || "",
          tenure: loanTenure,
          downPayment: eligibilityAndScore.requiredDownPayment,
          referenceId: referenceId,
          amount: eligibilityAndScore.requiredDownPayment,
        });
        updateMandateUrl = createEmandate.data?.data?.mono_url || "";
      }
      if (mandate[0].status == "Active" && regenerateMandate==false) {
        // chech if direct pay exists for the mandate
         await directPayService.regenerateDirectPay(
          mandate[0].id
        );
        
          // initiate direct pay
          const directPay = await this.initiateUpfrontPayment(id);
          if (directPay.success && directPay.data?.directPay) {
            updateMandateUrl =
              (directPay.data.directPay as { monoUrl?: string | null })
                .monoUrl || "";
          }
        
      }
    } else {
      const createEmandate = await accountDetailsService.createVariableMandate(
        process.env.MONO_CUSTOMER_ID_FOR_TEST ||
          accountDetails.data?.data?.customer?.id ||
          "",
        Math.ceil(Number(eligibilityAndScore.monthlyRepayment) * 100),
        new Date().toISOString(),
        referenceId
      );

      await invoiceMandateService.createInvoiceMandate({
        invoiceId: id,
        monoMandateId: createEmandate.data?.data?.mandate_id || "",
        monoAccountId: accountDetails.data?.data?.account?.id || "",
        monoCustomerId:
          process.env.MONO_CUSTOMER_ID_FOR_TEST ||
          accountDetails.data?.data?.customer?.id ||
          "",
        buyerId: buyerId,
        referenceId: referenceId,
        amount: eligibilityAndScore.monthlyRepayment,
        updateMandateUrl: createEmandate.data?.data?.mono_url,
        tenure: loanTenure,
        downPayment: eligibilityAndScore.requiredDownPayment,
        status: MandateStatus.Pending,
      });
      updateMandateUrl = createEmandate.data?.data?.mono_url || "";
    }
    // initiate mandate

    // perform merchant payment

    return {
      success: true,
      message: "Invoice updated successfully",
      data: {
        invoice: updatedInvoice,
        updateMandateUrl: updateMandateUrl,
      },
    };
  }

  async validateMandate({
    invoiceId,
    referenceId,
  }: {
    invoiceId?: string;
    referenceId?: string;
  }) {
    let mandate: any;

    if (referenceId) {
      mandate = await invoiceMandateService.getMandateByReferenceId(
        referenceId
      );
    }
    if (invoiceId) {
      const mandates = await invoiceMandateService.getMandatesByInvoiceId(
        invoiceId
      );
      if (mandates?.length > 0) {
        mandate = mandates[0];
      }
    }
    if (!mandate) {
      throw new Error("Mandate not found");
    }
    const mandateId = mandate.monoMandateId;
    const mandateStatus = mandate.status;
    const mandateAmount = mandate.amount;
    const mandateTenure = mandate.tenure;
    const mandateDownPayment = mandate.downPayment;
    const mandateReferenceId = mandate.referenceId;
    const mandateInvoiceId = mandate.invoiceId;
    const mandateBuyerId = mandate.buyerId;
    const mandateMonoAccountId = mandate.monoAccountId;
    const mandateMonoCustomerId = mandate.monoCustomerId;
    const invoiceAmount = mandate.invoice.amount;
    const monoMandate = await accountDetailsService.getMonoMandateById(
      mandateId
    );
    if (!monoMandate) {
      throw new Error("Mono mandate not found");
    }
    const monoMandateStatus = monoMandate.data?.data?.status;
    const monoMandateApproved = monoMandate.data?.data?.approved;
    if (monoMandateApproved) {
      //upd
      await invoiceMandateService.updateInvoiceMandate(mandate.id, {
        status: MandateStatus.Active,
      });
    }
    const eligibilityAndScore =
      await loanSettingService.liveEligibilityPurchase({
        purchaseAmount: Number(invoiceAmount),
        downPaymentAmount: mandateDownPayment,
        months: mandateTenure,
        buyerId: mandateBuyerId,
      });
    if (!eligibilityAndScore) {
      throw new Error("Eligibility and score not found");
    }

    return {
      ...monoMandate,
      eligibilityAndScore: {
        ...eligibilityAndScore,
        invoiceId: mandateInvoiceId,
        mandateId,
        referenceId,
      },
    };
  }

  async initiateUpfrontPayment(invoiceId: string) {
    const referenceId = generateShortReferenceId();
    const invoice = await prisma.invoice.findUnique({
      where: { id: invoiceId },
    });
    if (!invoice) {
      throw new Error("Invoice not found");
    }
    const mandate = await invoiceMandateService.getMandatesByInvoiceId(
      invoiceId
    );
    if (mandate?.length === 0) {
      throw new Error("Mandate not found");
    }
    const mandateDownPayment = mandate[0].downPayment;
    const mandateTenure = mandate[0].tenure;
    const mandateBuyerId = mandate[0].buyerId;
    const mandateMonoAccountId = mandate[0].monoAccountId;
    const mandateMonoCustomerId = mandate[0].monoCustomerId;
    const eligibilityAndScore =
      await loanSettingService.liveEligibilityPurchase({
        purchaseAmount: Number(invoice.amount),
        downPaymentAmount: Number(mandateDownPayment),
        months: Number(mandateTenure),
        buyerId: mandateBuyerId,
      });
    if (!eligibilityAndScore) {
      throw new Error("Eligibility and score not found");
    }

    // check if direct pay exists for the mandate
    await directPayService.regenerateDirectPay(
      mandate[0].id
    );
   
    // Check if the result has the required properties (complex type)
    // Type guard to narrow the type
    if (
      typeof eligibilityAndScore !== "object" ||
      !("requiredDownPayment" in eligibilityAndScore) ||
      !("adminCharge" in eligibilityAndScore) ||
      !("insurance" in eligibilityAndScore)
    ) {
      throw new Error(
        "Eligibility and score result does not contain required payment information"
      );
    }

    // TypeScript now knows these properties exist
    const result = eligibilityAndScore as {
      requiredDownPayment: number;
      adminCharge: number;
      insurance: number;
    };

    const amount =
      Number(result.requiredDownPayment) +
      Number(result.adminCharge) +
      Number(result.insurance);

    const directPay = await directPayService.initiateMonoDirectPay({
      amount: amount * 100,
      customerId: mandateMonoCustomerId,
      reference: referenceId,
      account: mandateMonoAccountId,
      description: `Upfront payment for invoice ${invoice.liftpayId}`,
    });
    if (!directPay.success) {
      throw new Error("Failed to initiate upfront payment");
    }
    // create direct pay
    const createdDirectPay = await directPayService.createDirectPay({
      invoiceId: invoiceId,
      mandateId: mandate[0].id,
      amount: amount,
      buyerId: mandateBuyerId,
      monoCustomerId: mandateMonoCustomerId,
      reference: referenceId,
      monoAccountId: mandateMonoAccountId,
      monoUrl: directPay.data.data.mono_url,
      status: DirectPayStatus.Pending,
    });
    if (!directPay.success) {
      throw new Error("Failed to create direct pay");
    }
    return {
      success: true,
      message: "Upfront payment initiated successfully",
      data: {
        directPay: { ...createdDirectPay, invoiceId, referenceId },
      },
    };
  }
  async validateMandateMandateDownPaymentAndCreateLoanInvoice({
    invoiceId,
    referenceId,
  }: {
    invoiceId?: string;
    referenceId?: string;
  }) {
    let mandate;
    if (invoiceId) {
      const invoiceMandate = await invoiceMandateService.getMandatesByInvoiceId(
        invoiceId
      );
      if (invoiceMandate?.length > 0) {
        mandate = invoiceMandate[0];
      }
    }
    if (referenceId) {
      try {
        mandate = await invoiceMandateService.getMandateByReferenceId(
          referenceId
        );
      } catch (error) {
        const directPay = await directPayService.getDirectPayByReference(
          referenceId
        );
        if (!directPay) {
          throw new Error("Direct pay not found");
        }
        const invoiceMandate =
          await invoiceMandateService.getMandatesByInvoiceId(
            directPay.invoiceId
          );
        if (invoiceMandate?.length > 0) {
          mandate = invoiceMandate[0];
        }
      }
    }

    if (!mandate) {
      throw new Error("Mandate not found");
    }
    if (mandate.status != "Active") {
      throw new Error("Mandate emandate not yet authorise");
    }
    // check upfront payment
    const upfrontPayment = await directPayService.getDirectPaysByMandateId(
      mandate.id
    );
    if (!upfrontPayment) {
      throw new Error("Upfront payment not found");
    }
    const finalizeResult = await this.finalizeAfterUpfrontAndMandate(
      mandate.id
    );
    return finalizeResult;
  }
  // ==================== ITEM CRUD ====================

  /**
   * Create item for an invoice
   */
  async createItem(invoiceId: string, input: CreateItemInput) {
    try {
      // Verify invoice exists
      const invoice = await prisma.invoice.findUnique({
        where: { id: invoiceId },
      });

      if (!invoice) {
        throw new Error("Invoice not found");
      }

      const item = await prisma.item.create({
        data: {
          invoiceId,
          description: input.description,
          quantity: input.quantity,
          amount: input.amount,
        },
        include: {
          invoice: {
            select: {
              id: true,
              liftpayId: true,
              customerName: true,
            },
          },
        },
      });

      return {
        success: true,
        message: "Item created successfully",
        data: item,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to create item",
      };
    }
  }

  /**
   * Get item by ID
   */
  async getItemById(id: string) {
    try {
      const item = await prisma.item.findUnique({
        where: { id },
        include: {
          invoice: {
            select: {
              id: true,
              liftpayId: true,
              customerName: true,
              status: true,
            },
          },
        },
      });

      if (!item) {
        throw new Error("Item not found");
      }

      return {
        success: true,
        data: item,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch item",
      };
    }
  }

  /**
   * Get all items for an invoice
   */
  async getItemsByInvoiceId(invoiceId: string) {
    try {
      const items = await prisma.item.findMany({
        where: { invoiceId },
        orderBy: { createdAt: "asc" },
      });

      return {
        success: true,
        data: items,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch items",
      };
    }
  }

  /**
   * Update item
   */
  async updateItem(id: string, input: UpdateItemInput) {
    try {
      const existingItem = await prisma.item.findUnique({
        where: { id },
      });

      if (!existingItem) {
        throw new Error("Item not found");
      }

      const item = await prisma.item.update({
        where: { id },
        data: input,
        include: {
          invoice: {
            select: {
              id: true,
              liftpayId: true,
              customerName: true,
            },
          },
        },
      });

      return {
        success: true,
        message: "Item updated successfully",
        data: item,
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to update item",
      };
    }
  }

  /**
   * Delete item
   */
  async deleteItem(id: string) {
    try {
      const existingItem = await prisma.item.findUnique({
        where: { id },
      });

      if (!existingItem) {
        throw new Error("Item not found");
      }

      await prisma.item.delete({
        where: { id },
      });

      return {
        success: true,
        message: "Item deleted successfully",
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to delete item",
      };
    }
  }

  // ==================== UTILITY METHODS ====================

  /**
   * Calculate invoice total from items
   */
  async calculateInvoiceTotal(invoiceId: string) {
    try {
      const items = await prisma.item.findMany({
        where: { invoiceId },
      });

      const total = items.reduce((sum, item) => {
        return sum + Number(item.amount) * item.quantity;
      }, 0);

      return {
        success: true,
        data: { total, itemCount: items.length },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to calculate invoice total",
      };
    }
  }

  /**
   * Get invoice statistics for a merchant
   */
  async getMerchantInvoiceStats(merchantId: string) {
    try {
      const [total, pending, paid, cancelled] = await Promise.all([
        prisma.invoice.count({ where: { merchantId } }),
        prisma.invoice.count({
          where: { merchantId, status: InvoiceStatus.Pending },
        }),
        prisma.invoice.count({
          where: { merchantId, status: InvoiceStatus.Paid },
        }),
        prisma.invoice.count({
          where: { merchantId, status: InvoiceStatus.Cancelled },
        }),
      ]);

      const totalAmount = await prisma.invoice.aggregate({
        where: { merchantId },
        _sum: { amount: true },
      });

      const paidAmount = await prisma.invoice.aggregate({
        where: { merchantId, status: InvoiceStatus.Paid },
        _sum: { amount: true },
      });

      const pendingAmount = await prisma.invoice.aggregate({
        where: { merchantId, status: InvoiceStatus.Pending },
        _sum: { amount: true },
      });

      return {
        success: true,
        data: {
          counts: {
            total,
            pending,
            paid,
            cancelled,
          },
          amounts: {
            total: Number(totalAmount._sum.amount || 0),
            paid: Number(paidAmount._sum.amount || 0),
            pending: Number(pendingAmount._sum.amount || 0),
          },
        },
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || "Failed to fetch invoice statistics",
      };
    }
  }
}

export const invoiceService = new InvoiceService();
